name: AntiMoni

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"

          if [ "$GITHUB_HEAD_REF" != "staging" ]; then
            echo "Solo se permite merge desde staging a main"
            exit 1
          fi
